### ISSUE TITLE
Help implement HackTimer using SharedWorker

### ISSUE THREAD

**Issue by ravelapraveen** [turuslan/HackTimer#15]
When you open more tabs (Like 10 .. 20 or more), with each tab opening a new worker to implement HackTimer, there is an impact on system performance.

Is it possible to utilize SharedWorker to implement HackTimer?

We hope this will help achieve the same functionality across all the tabs using a single shared worker.
If possible can you please suggest the changes required?

Can you share your thoughts?

**Comment by turuslan** [comment]
Yes it's possible to use SharedWorker.

It looks easy to implement - just add code to route requests from different tabs to worker and store tab timers data associated with tab.

But I suppose there may be some issues:

- In general case most of opened tabs do not belong to the same domain so they won't share worker due to cross-origin policy.
- In general case it may be non trivial task to determine whether tab is closed, so memory leaks will occur.

But those issues can be avoided by adapting code for specific application.
